repos:
-   repo: https://github.com/psf/black
    rev: stable
    hooks:
    - id: black
      language_version: python3.7
-   repo: https://github.com/PyCQA/bandit
    rev: 1.6.2
    hooks:
    - id: bandit
